
(def listen (net/listen (net/bind (net/socket) "127.0.0.1" 12345) 10))
(def conn (net/connect (net/socket) "127.0.0.1" 12345))
(def client (net/accept listen))
(net/send client "Hello from server!")
(net/send conn "Hello from client!")
(println (net/recv client))
(println (net/recv conn))
(net/close client)
(net/close conn)
(net/close listen)
